// Creates the teacher login on a branch that gets no sample data:
// main, when the app goes live. Refuses if the branch already has a teacher.
// Usage: node tools/create-teacher.ts --env .env.main
// The login goes to tools/out/logins.<branch>.md (git-ignored), never printed or committed.
import { randomBytes } from 'node:crypto';
import { mkdirSync, writeFileSync } from 'node:fs';
import pg from 'pg';
import { hashSecret } from '../api/src/lib/auth.ts';

const args = process.argv.slice(2);
const envFile = args.includes('--env') ? args[args.indexOf('--env') + 1] : '.env.local';
process.loadEnvFile(envFile);
const branch = process.env.NEON_BRANCH ?? 'unknown';

const db = new pg.Client({ connectionString: process.env.DATABASE_URL_UNPOOLED ?? process.env.DATABASE_URL });
await db.connect();
try {
  await db.query('begin');
  const existing = (await db.query(`select username from users where role = 'teacher' limit 1`)).rows[0];
  if (existing) throw new Error(`Branch ${branch} already has a teacher ("${existing.username}"). Nothing changed.`);
  const password = randomBytes(9).toString('base64url');
  const { hash, salt } = await hashSecret(password);
  const teacher = (await db.query(
    `insert into users (role, username, display_name, secret_hash, secret_salt)
     values ('teacher', 'coreacademy', 'Core Academy', $1, $2) returning id`,
    [hash, salt],
  )).rows[0];
  // The first tuition (made by migration 012) gets its owner.
  await db.query(`insert into memberships (tuition_id, user_id, role, status) values ('00000000-0000-4000-8000-0000000000a1', $1, 'owner', 'active')`, [teacher.id]);
  await db.query(`update tuitions set created_by = $1 where id = '00000000-0000-4000-8000-0000000000a1' and created_by is null`, [teacher.id]);
  // Written before the commit, so a saved account always has its password on disk.
  mkdirSync('tools/out', { recursive: true });
  writeFileSync(
    `tools/out/logins.${branch}.md`,
    `# Core Academy teacher login (${branch} branch)\n\nGenerated by tools/create-teacher.ts. Not committed.\n\n` +
      `Teacher: username coreacademy, password ${password} (change it in Settings)\n`,
  );
  // Read by tools/api-test.ts and tools/ai-test.ts.
  writeFileSync(`tools/out/sample-logins.${branch}.json`, JSON.stringify({ teacher: { username: 'coreacademy', password }, students: [] }, null, 2));
  await db.query('commit');
  console.log(`Teacher login created on branch ${branch}, written to tools/out/logins.${branch}.md`);
} catch (e) {
  await db.query('rollback');
  throw e;
} finally {
  await db.end();
}
