// Generates lib/ui/icons.dart for the app and the admin app: Phosphor Light icons (MIT) as plain
// IconData on a bundled font. phosphor_flutter 2.1.0 subclasses IconData, which is a final class
// on Flutter 3.47, so the package cannot compile; its font and codepoints are still right.
// Run from the project root:
//   node tools/gen-icons.mjs
import { copyFileSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const pkg = join(process.env.LOCALAPPDATA, 'Pub', 'Cache', 'hosted', 'pub.dev', 'phosphor_flutter-2.1.0');
const src = readFileSync(join(pkg, 'lib', 'src', 'phosphor_icons_light.dart'), 'utf8');

const names = [
  'x', 'arrowLeft', 'arrowRight', 'arrowUp', 'arrowDown', 'flag', 'timer', 'listNumbers', 'house', 'users', 'scan',
  'books', 'exam', 'image', 'images', 'pencilSimple', 'check', 'caretRight', 'caretDown', 'caretUp', 'plus', 'minus',
  'camera', 'filePdf', 'fileArrowUp', 'userCircle', 'userPlus', 'signOut', 'arrowsClockwise', 'warning', 'backspace',
  'copy', 'shareNetwork', 'trash', 'gear', 'magnifyingGlass', 'clock', 'eye', 'eyeSlash', 'lock', 'key', 'notePencil',
  'checkCircle', 'prohibit', 'arrowCounterClockwise', 'dotsThree', 'info', 'calendar', 'chartBar', 'student',
  'chalkboardTeacher', 'downloadSimple', 'export', 'listChecks', 'squaresFour', 'sortAscending', 'funnel', 'crop',
  'fileText', 'arrowCircleUp', 'dotsThreeVertical', 'sparkle', 'wifiSlash', 'clockCountdown', 'caretLeft', 'warningCircle',
];

// The developer's admin app (admin/).
const admin = [
  'x', 'arrowLeft', 'gauge', 'users', 'deviceMobile', 'hardDrives', 'listBullets', 'arrowsClockwise', 'magnifyingGlass',
  'caretDown', 'caretRight', 'lockKey', 'lockKeyOpen', 'warning', 'checkCircle', 'signOut', 'gear', 'arrowCircleUp',
  'database', 'cloud', 'lightning', 'robot', 'bell', 'bellSlash', 'clock', 'key', 'userCircle', 'exam', 'fileText',
  'bug', 'globe', 'check', 'copy', 'circle', 'buildings', 'currencyInr', 'pulse',
];

function write(target, list, fontDir) {
  const lines = list.map((n) => {
    const m = src.match(new RegExp(`static const ${n} = PhosphorFlatIconData\\((0x[0-9a-f]+), 'Light'\\);`));
    if (!m) throw new Error(`icon not found: ${n}`);
    return `  static const ${n} = IconData(${m[1]}, fontFamily: _family);`;
  });
  writeFileSync(
    target,
    `// Generated by tools/gen-icons.mjs. Phosphor Light icons (MIT licence, assets/fonts/PHOSPHOR-LICENSE.txt).
import 'package:flutter/widgets.dart';

/// Thin-stroke icons (the guide bans 2px default sets).
abstract final class Ph {
  static const _family = 'PhosphorLight';

${lines.join('\n')}
}
`,
  );
  copyFileSync(join(pkg, 'lib', 'fonts', 'Phosphor-Light.ttf'), join(fontDir, 'PhosphorLight.ttf'));
  copyFileSync(join(pkg, 'LICENSE'), join(fontDir, 'PHOSPHOR-LICENSE.txt'));
  console.log(`${target}: ${list.length} icons; font and licence copied`);
}

write('app/lib/ui/icons.dart', names, 'app/assets/fonts');
// The admin app shares the main app's components, so it needs every icon they use, plus its own.
write('admin/lib/ui/icons.dart', [...new Set([...names, ...admin])], 'admin/assets/fonts');
